<?php
$config['api'] = array(
	'providers'=>array(
		'176.121.192.112'=>array('name'=>'Shakhtersk','type'=>'ProviderJSON'),
		'192.168.14.1'=>array('name'=>'Armax','type'=>'ProviderXML'),
		'212.87.166.123'=>array('name'=>'kite','type'=>'ProviderXML'),
		'X.X.X.X'=>array('name'=>'BANK','type'=>'ProviderXML'),
		'195.211.23.206'=>array('name'=>'BANK_V1.0.3','type'=>'ProviderXXX'),
		'176.121.197.130'=>array('name'=>'AsterHr','type'=>'ProviderJSON'),
		'176.121.192.6'=>array('name'=>'nagios','type'=>'ProviderJSON'),
	),
	'restrict'=>array( // методы разрешенные конкретному провайдеру
		'BANK'=>array('check','pay','get')
	),
	'options'=>array(
		'AsterHr'=>array(
			'input'=>array(
				'type'=>'from',
			),
			'output'=>array(
				'get'=>array(
					'result'=>'result',
					'data'=>array(
						'deposit'=>'deposit',
						'expired'=>'expired',
						'phone'=>'phone',
						'fio'=>'fio',
						'tarif'=>'tarif'
					)
				),
			)
		),
		'CityPay'=>array(
			'result'=>array('NONE'=>21,'OK'=>0,'ERROR'=>1,'FATAL'=>2,'SUMM'=>1),
			'method'=>array('check'=>'get','PayDayReport'=>'report'),
			'reverce_result_on_pay_exists'=>1,
			'input'=>array(
				'QueryType'=>'method',
				'TransactionId'=>'payment_id',
				'Account'=>'contract',
				'PayElementId'=>'service',
				'Amount'=>'money',
				'TransactionDate'=>'paytime',
				'CheckDateBegin'=>'begin',
				'CheckDateEnd'=>'end',
			),
			'output'=>array(
				'get'=>array(
					'result'=>'ResultCode',
					'payment_id'=>'TransactionId',
					'Fields'=>array(
						'fio'=>'field1 name=fio',
						'address'=>'field2 name=address',
						'tarif'=>'field3 name=tarif'
					),
					'Comment'=>'note'
				),
				'pay'=>array(
					'card'=>'TransactionId',
					'unique_id'=>'TransactionExt',
					'money'=>'Amount',
					'result'=>'ResultCode',
					'note'=>'Comment',
				),
				'report'=>array(
					'card'=>'TransactionId',
					'contract'=>'Account',
					'money'=>'Amount',
					'result'=>'ResultCode',
					'paytime'=>'TransactionDate',
					'service'=>'PayElementId',
					'note'=>'Comment',
					'element'=>'Payment',
				),
			)
		),
		'Armax'=>array(
			'result'=>array('NONE'=>21,'OK'=>0,'ERROR'=>1,'FATAL'=>2,'SUMM'=>1),
			'method'=>array('check'=>'get','PayDayReport'=>'report'),
			'reverce_result_on_pay_exists'=>1,
			'input'=>array(
				'QueryType'=>'method',
				'TransactionId'=>'payment_id',
				'Account'=>'contract',
				'PayElementId'=>'service',
				'Amount'=>'money',
				'TransactionDate'=>'paytime',
				'CheckDateBegin'=>'begin',
				'CheckDateEnd'=>'end',
			),
			'output'=>array(
				'get'=>array(
					'result'=>'ResultCode',
					'payment_id'=>'TransactionId',
					'Fields'=>array(
						'fio'=>'field1 name=fio',
						'address'=>'field2 name=address',
						'tarif'=>'field3 name=tarif'
					),
					'Comment'=>'note'
				),
				'pay'=>array(
					'card'=>'TransactionId',
					'unique_id'=>'TransactionExt',
					'money'=>'Amount',
					'result'=>'ResultCode',
					'note'=>'Comment',
				),
				'report'=>array(
					'result'=>'ResultCode',
					'report'=>'Payment',
					'card'=>'TransactionId',
					'contract'=>'Account',
					'paytime'=>'TransactionDate',
					'money'=>'Amount',
					'service'=>'PayElementId',
				),
			)
		),
		'Shakhtersk'=>array(
			'result'=>array('NONE'=>0,'OK'=>1,'ERROR'=>2,'FATAL'=>2,'SUMM'=>2),
			'input'=>array(
				'sum'=>'money',
				'date'=>'paytime',
				'type'=>'from',
			),
			'redirect'=>array(
				'pigin'=>'http://domain.net/api/index.php?command=pay&account=:CONTRACT:&sum=:MONEY:&txn_id=:PAYMENT_ID:&type=:FROM:',
			),
			'output'=>array(
				'check'=>array(
					'result'=>'result',
					'uid'=>'uid'
				),
				'get'=>array(
					'result'=>'result',
					'data'=>array(
						'deposit'=>'deposit',
						'expired'=>'expired',
						'phone'=>'phone',
						'fio'=>'fio',
						'tarif'=>'tarif',
						'email'=>'email'
					)
				),
				'pay'=>array(
					'result'=>'result',
					'note'=>'note',
					'data'=>array(
						'unique_id'=>'id',
						'card'=>'payment_id',
						'money'=>'sum',
						'acttime'=>'private_date',
						'paytime'=>'date',
						'from'=>'type'
					),
				)
			)
		),
		'BANK'=>array(
			'result'=>array('NONE'=>2,'OK'=>0,'ERROR'=>1,'FATAL'=>2,'SUMM'=>1),
			'reverce_result_on_pay_exists'=>1,
			'input'=>array(
				'command'=>'method',
				'txn_id'=>'payment_id',
				'account'=>'contract',
				'sum'=>'money',
				'txn_date'=>'paytime',
			),
			'output'=>array(
				'check'=>array(
					'result'=>'result',
				),
				'get'=>array(
					'result'=>'result',
					'data'=>array(
						'deposit'=>'deposit',
						'expired'=>'expired',
						'phone'=>'phone',
						'fio'=>'fio',
						'tarif'=>'tarif',
						'email'=>'email'
					)
				),
				'pay'=>array(
					'card'=>'ufc_txn_id',
					'unique_id'=>'prv_txn',
					'acttime'=>'prv_txn_date',
					'money'=>'sum',
					'result'=>'result',
					'note'=>'note',
				)
			)
		),
		'BANK_V1.0.3'=>array(
			'result'=>array('NONE'=>100,'OK'=>0,'ERROR'=>105,'FATAL'=>105,'SUMM'=>106),
			'reverce_result_on_pay_exists'=>1,
			'input'=>array(
				'command'=>'method',
				'PayerCode'=>'contract',
				'ServiceName'=>'service',
				'NTran'=>'payment_id',
				'DStart'=>'paytime',
				'DTran'=>'paytime',
				'S'=>'money',
			),
			'output'=>array(
				'check'=>array(
					'result'=>'Status',
					'fio'=>'FIO',
				),
				'pay'=>array(
					'result'=>'Status',
					'card'=>'NTran',
					'fio'=>'FIO',
					'money'=>'S',
				),
				'removepay'=>array(
					'result'=>'Status',
					'contract'=>'PayerCode',
					'card'=>'NTran',
					'fio'=>'FIO',
				),
				'paymentlist'=>array(
					'result'=>'Status',
					0=>'list'
				),
				'default'=>array(
					'result'=>'Status',
				),
			)
		),
		'nagios'=>array(
			'input'=>array(
				'type'=>'from',
			),
			'output'=>array(
				'sms'=>array(
					'result'=>'result',
				),
			)
		),
	)
);
$config['api']['db'] = $config['db'];
$config['api']['db_cards'] = $config['db_cards'];
?>
